name: code_general_impots
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1.1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  http: ^0.13.4
  simple_html_css: ^3.0.1+1
  # html: ^0.15.0
  # flutter_widget_from_html: ^0.8.3
  # flutter_html: ^2.2.0
  # flutter_html_view: ^0.5.11
  shared_preferences: ^2.0.9
  flutter_local_notifications: ^9.3.3
  font_awesome_flutter: ^9.2.0
  flutter_localizations:
    sdk: flutter
  collection: any
  rounded_expansion_tile: ^0.0.13
  flutter_speed_dial: ^5.0.0+1
  animated_splash_screen: 
  

dev_dependencies:
  intl: ^0.17.0-nullsafety.2
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app-logo.png"

  # flutter_lints: ^1.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700